language: python
python:
- 3.8
- 3.7
branches:
  only:
  - master
services:
  - docker
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry build
- poetry run black --check
- poetry run flake8 --max-line-length=100 --ignore=E501,W293,E303,W291,W503,E203,E731,E231,E721,E722,E741 .
- poetry run mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers --warn-unreachable . 
- poetry run pytest -v --cov {{cookiecutter.package_name}}
- poetry run coverage html
- docker build -t {{cookiecutter.repo_name}}:${TRAVIS_COMMIT}
# TODO: If you want to use a code-coverage service, e.g. coveralls: https://coveralls.io/
#       Uncomment the 'after_success' section below.
#       NOTE: Make sure you `poetry add --dev coveralls` !!
#             And, ensure that coveralls knows about this repository.
#after_success:
#- poetry run coveralls
# TODO: This is a good place to check if you're on a tagged commit on the `main` branch.
#
#       And, if so, publish to PyPI with:
#       >> poetry build && poetry publish
#       If you want to do this, make sure that:
#         1. You have a PyPI login
#         2. You add your API token as a secret in Travis CI.
#         3. Follow https://python-poetry.org/docs/repositories/#configuring-credentials
#{%- if cookiecutter.project_type.startswith("docker_exe") %}
#      And, if so, publish your docker image to Docker Hub:
#      >> docker push {{cookiecutter.repo_name}}:${TRAVIS_COMMIT}
#      If you want to do this, make sure that:
#         1. You have a Docker Hub login
#         2. You have saved your username and password as secret env vars in Travis CI.
#         3. You do `docker login` before pushing.
{%- endif %}
